### ISSUE TITLE
Using ~ in path settings on Windows doesn't work for me

### ISSUE THREAD

**Issue by qmacro** [bit101/STProjectMaker#31]
Hi 

Really liking the plugin, thank you. 

I use ST2 on W7 (unfortunately) and have found that using ~ in settings doesn't work right - the userdir is not expanded correctly either for the `template_path` or the `default_project_path` settings. 

I've made some exploratory mods to projectmaker.py but didn't want to send a pull request just yet as I don't have the facility to test the changes on non-Windows platforms.

https://github.com/qmacro/STProjectMaker/commit/f45e2ae60d3c2864bcc929c22eacd95ea90d6423

With these mods it does what I expect it to do: honour the ~ prefixes (as in the example config below) properly in my W7 setup.

```
{
    "default_project_path": "~/Dropbox/shed/",
    "template_path": "~/AppData/Roaming/Sublime Text 2/Packages/SublimeUI5/Templates"
}
```

Any light you could shed on this for me would be useful.

Thanks
dj

**Comment by pykong** [comment]
fixed by #38
