### ISSUE TITLE
Doesn't appear in package control

### ISSUE THREAD

**Issue by lunelson** [bit101/STProjectMaker#41]
Unfortunately. It's listed at packagecontrol.io but not when loading the install menu from within the latest build of ST3. 

Also: in the README it's written to look for "STPackageMaker", which I assume should be "STProjectMaker"

**Comment by bullitbd** [comment]
ST3 - I found it in the install menu & installed - under "STProjectMaker", of course.

**Comment by bit101** [comment]
Thanks. Fixed the readme.

**Comment by lunelson** [comment]
I'm on build 3114 and I still don't get it listed under "Install Package" 🤔

**Comment by bit101** [comment]
Not sure what to tell you, I just installed it myself to be sure. build 3120.

Stupid question, but I have to ask... are you sure it's not already installed? Installed packages won't show up in the install list. At any rate, it's validly in the packagecontrol list. If it's not showing up on some systems/builds, there's nothing I can do. It's just an entry in a manifest. The entry is there and working as far as I can tell. If something else is broken it's either with ST3 or packagecontrol.

**Comment by lunelson** [comment]
Argh sorry @bit101 your instincts are better than mine. That was the reason and I should have known better cause this has bitten me once before too. I must have installed this packages quite some time ago and forgotten about it.
