### ISSUE TITLE
Is this Project still alive?

### ISSUE THREAD

**Issue by pykong** [bit101/STProjectMaker#45]
@bit101 Thank you very much for putting the effort in to develop this near little plugin.
Among all templating plugins for SublimeText I have found this to be best suited for my purposes.

I like to contribute some improvements, but regarding that the last commit is from mid 2016, I wonder whether those would be reviewed or merged anytime. I mean there are PRs from 2014.

I know maintaining a project can be burdensome, but in all fairness communicate to users the current state of the project and where it is headed.

In case you need a co-maintainer I am willing to help.

**Comment by bit101** [comment]
Thanks for the comments. I'm glad you like the plugin.
No, the project is not active any more. I don't currently use Sublime, myself. I'd be happy to have you help maintain it if you're into it though.

**Comment by bit101** [comment]
You are now a collaborator. Let me know if that gives you all the access you need.

**Comment by pykong** [comment]
Great thank you for your trust!
I will let you know in case I require any other user privilege.

**Comment by pykong** [comment]
@bit101 I'd like to add the topics:
Sublime Text 3, template, project and project-template to this repo to make it more friendly to GitHub's search engine. Could you either please add those topics yourself or grant me the respective permissions?
Thank you!
